# Site settings
title: Christian van Onzenoodt // onc
email: onze@onze.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onze.io" # the base hostname & protocol for your site
twitter_username: On_Ze
github_username:  onc

collections:
  projects:
    output: true
    permalink: /projects/:path

# Build settings
markdown: kramdown
