# Site settings
title: Christian van Onzenoodt
email: c.onzenoodt@posteo.de
description: Christian van Onzenoodt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onze.io" # the base hostname & protocol for your site
instagram_username: onzeotherhand
scholar_url: scholar.google.com/citations?user=9wi8dSgAAAAJ&hl=en
git_url: github.com/onc
linkedin_url: www.linkedin.com/in/christian-van-onzenoodt-21420024a/

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
