# Site settings
title: Christian van Onzenoodt // onze
email: onze@onze.io
description: > # this means to ignore newlines until "baseurl:"
   Webpage of Christian van Onzenoodt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onze.io" # the base hostname & protocol for your site
instagram_username: onzeotherhand
git_url: github.com/onc

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
